version: "3"
services:
  dotnet-api:
    image: ${DOCKER_REGISTRY-}dotnet-api
    build:
      context: .
      dockerfile: /src/microservices/dotnet-api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  react-app:
    image: ${DOCKER_REGISTRY-}react-application
    build:
      context: .
      dockerfile: /src/react-application/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
